# Generated by Django 2.1.5 on 2019-04-02 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_category', models.CharField(max_length=200)),
                ('category_summery', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='IdeaSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('idea_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.IdeaCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='MyIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=200, verbose_name='Title')),
                ('idea_conttent', models.TextField(verbose_name='Content')),
                ('idea_published', models.DateTimeField(default=datetime.datetime(2019, 4, 2, 20, 16, 19, 503477), verbose_name='date published')),
                ('idea_slug', models.CharField(default=main.models.f, max_length=200, verbose_name='url')),
                ('idea_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.IdeaSeries', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'My idea',
            },
        ),
    ]
