# Generated by Django 2.1.5 on 2019-04-02 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myidea',
            name='idea_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 20, 16, 37, 698419), verbose_name='date published'),
        ),
    ]
