# Generated by Django 2.1.5 on 2019-04-02 20:53

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190402_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myidea',
            name='idea_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 20, 53, 42, 192362), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='myidea',
            name='idea_publisher',
            field=models.CharField(default=main.models.u, max_length=200, verbose_name='Publisher'),
        ),
    ]
