# Generated by Django 2.1.5 on 2019-04-02 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190402_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myidea',
            name='idea_publisher',
        ),
        migrations.AlterField(
            model_name='myidea',
            name='idea_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 21, 0, 33, 65585), verbose_name='date published'),
        ),
    ]
