# Generated by Django 2.1.5 on 2019-05-31 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190515_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200)),
                ('post_title', models.CharField(max_length=200)),
                ('reply_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'دیدگاه ها',
            },
        ),
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name_plural': 'حمایت های مالی'},
        ),
        migrations.AlterField(
            model_name='myidea',
            name='idea_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 15, 14, 13, 822439), verbose_name='date published'),
        ),
    ]
