# Generated by Django 2.2.10 on 2020-06-19 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200327_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myidea',
            name='idea_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 10, 0, 49, 837833), verbose_name='date published'),
        ),
    ]
